### ISSUE TITLE
[FEATURE] Names of the environment variable are somewhat generic

### ISSUE THREAD

**Issue by jack1142** [apoclyps/reviews#155]
**Is your feature request related to a problem? Please describe.**
I think that the currently used env var names (`PATH_TO_CONFIG`, `DEFAULT_PAGE_SIZE`, `DELAY_REFRESH`, `REPOSITORY_CONFIGURATION`, `LABEL_CONFIGURATION`) are rather generic names. While I don't think it's likely that they would conflict with some other tool, I do think that this makes it hard to go through the list of environment variables you have set and know *why* you have set that environment variable.
It's less of a problem in Linux environments where you put those in a bash script that can have comments, but on Windows, you generally set them from this place and there's no place for comments:
![image](https://user-images.githubusercontent.com/6032823/120246488-aaa50800-c270-11eb-9cab-b5e466e1c241.png)

**Describe the solution you'd like**
I think that the environment variable names should be prefixed with the name of the project, i.e. `REVIEWS_PATH_TO_CONFIG`. Perhaps some other prefix would work better here but the idea is to have one so that it's easily identifiable.

**Comment by apoclyps** [comment]
I agree. The environment variables would benefit from having a `REVIEWS_` prefix added to help namespace application configuration. I rarely use Windows for development but I can see how this could be problematic. Thanks for raising this as an issue 👍 

Feel free to open a PR with the changes - if you would like to add them as a contribution. Alternatively, I can take a look at adding it tomorrow after work

**Comment by apoclyps** [comment]
@jack1142 these changes will be available in the next release. It will be `0.2.0` as it contains breaking changes to the existing configuration.
