### ISSUE TITLE
[Feature] Add flag to dashboard to hide/show authors pull requests

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/reviews#181]
**Is your feature request related to a problem? Please describe.**
When reviewing pull requests, occasionally I only need to see the pull requests of others to review their code, or pull requests of my own to ship a pull request that is ready.

**Describe the solution you'd like**
Whilst watching repositories in which I have contributed pull requests, I would like to filter the results to hide all pull requests authored by github user or display only the pull requests authored by my gitub user. 

**Additional context**
* flags provided to the render functions to show/hide pull requests from the author will need to be included in both render functions: https://github.com/apoclyps/reviews/blob/main/reviews/commands.py#L45-L70

**Comment by paulosgf** [comment]
Hi @apoclyps !
I started to work on this issue this week and already have a fixed solution (without flag) ready for Github. You don't like to reopen and assign it to me?

**Comment by apoclyps** [comment]
@paulosgf sure, I'm happy to reopen it 😄

**Comment by paulosgf** [comment]
Thank's!

**Comment by paulosgf** [comment]
Hi @apoclyps! 
Sorry, but this project is too complex for me. I'm seeking first-time-only fixes.
Thanks for your understanding!

**Comment by apoclyps** [comment]
@paulosgf I'd be happy to answer any questions you have or provide clarification around the complex areas. If that helps.

Any and all feedback is appreciated :)

**Comment by paulosgf** [comment]
@apoclyps , sorry for the delay in response.
I managed to just implement to show the PR author on Github. For now without the command line option.
If you have a development branch, I can send it to you to take a look at.

**Comment by apoclyps** [comment]
I don't have a development branch but you're welcome to open a pull request as a draft against main with the changes.

**Comment by paulosgf** [comment]
As for the implementation in Gitlab, I'm getting some errors regarding an object type shared between Gitlab and Github. I had new ideas and I'll test it first, then I'll give you more details of the difficulty, ok?

**Comment by paulosgf** [comment]
> I don't have a development branch but you're welcome to open a pull request as a draft against main with the changes.

Ok!

**Comment by paulosgf** [comment]
Thanks for listening!
