### ISSUE TITLE
[Feature] Add a version command

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/reviews#51]
**Is your feature request related to a problem? Please describe.**
I would like to be able to list the installed version of `reviews` by typing `reviews --version` to see the installed version.

**Describe the solution you'd like**
using the latest version of `reviews`, I would like to type `reviews` and see `--version` as an option for displaying the current version.

when executing `reviews --version`, It should display the currently installed version defined within `reviews/version.py`.

**Additional context**
Adding a new command should be included in https://github.com/apoclyps/reviews/blob/main/cli.py

**Comment by adam-tokarski** [comment]
Done with #52

**Comment by apoclyps** [comment]
Built and tested locally using version 0.1.3:

![image](https://user-images.githubusercontent.com/1443700/116305698-0aa11e00-a79c-11eb-81de-e04c95b0e472.png)

**Comment by apoclyps** [comment]
Thank you again @adam-tokarski for this pull request. 

This feature is now implemented in master (closed by #52) and will ship in the next release: `0.1.4`.
