### ISSUE TITLE
Request for PAT requirements documentation

### ISSUE THREAD

**Issue by MindNumbing** [apoclyps/reviews#633]
**Is your feature request related to a problem? Please describe.**

Currently it is difficult to know what the project requires in terms of PAT access. IE if it requires read vs read/write or which specific sections IE PRs / issues etc.

**Describe the solution you'd like**

Ideally the README would be updated with the required token requirements for the project.

**Comment by apoclyps** [comment]
@MindNumbing thanks for raising this issue. I'll take a look at adding it to the readme soon.

**Comment by apoclyps** [comment]
@MindNumbing does the following documentation help in https://github.com/apoclyps/reviews/pull/634? i'd love to know your thoughts on how this could be improved

the old style of personal access tokens aren't ideal for granting all the read-only access required - I've yet to find a way to make it work without giving full `repo` and `admin:org` permissions. Hopefully the new beta tokens improve upon :crossed_fingers:

**Comment by apoclyps** [comment]
going to close this out, for now, that #634 is merged however if there are any improvements to be made, feel free to re-open it.
