### ISSUE TITLE
[Feature] Add flag to perform a single dashboard update - render cycle

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/reviews#70]
**Is your feature request related to a problem? Please describe.**
By default the TUI runs continuously in a loop until cancelled by a user, however, I would like to run `reviews dashboard` with a `--no-refresh` to display the output in the terminal once.  

**Describe the solution you'd like**
When I type `reviews dashboard --no-refresh the TUI loads as expected, and exits after completing the first render.

**Additional context**

the `--no-refresh` command will need to be configured here: https://github.com/apoclyps/reviews/blob/9593f4638d6333738521bb78bb023045744f6a7e/cli.py#L19-L21

see Click arguments for implementation: https://click.palletsprojects.com/en/7.x/arguments/

the loop should be modified to loop continuously if `no-refresh` is not provided. 
https://github.com/apoclyps/reviews/blob/9593f4638d6333738521bb78bb023045744f6a7e/reviews/tasks.py#L84

**Comment by yushao2** [comment]
@apoclyps do you mean options instead? 

https://click.palletsprojects.com/en/7.x/options/#options

**Comment by yushao2** [comment]
> @apoclyps do you mean options instead?
> 
> https://click.palletsprojects.com/en/7.x/options/#options

I've started working on this, but am currently facing an issue where when I quit off the main loop, the last refreshed display goes away with it and thus is useless -- I've referred to the docs regarding transient display but that's not really helpful too. Will see if there's any other way to accomplish this

**Comment by apoclyps** [comment]
Yes, thanks for making a note that options was the correct usage here.

I'll check out your WIP shortly and see if there is any way we can do this. It may be a limitation of the library being used or a feature that isn't generally supported.

**Comment by apoclyps** [comment]
This may not be possible using the existing classes in the rich library because of the following:


> The live display will persist for the duration of the context. You can update the renderable to update the display

https://rich.readthedocs.io/en/stable/live.html#basic-usage

> transient (bool, optional): Clear the renderable on exit (has no effect when screen=True). Defaults to False.

https://github.com/willmcgugan/rich/blob/f513abd35fdacccdc6fcbcc6989b5792b75ec97a/rich/live.py#L43

**Comment by yushao2** [comment]
> This may not be possible using the existing classes in the rich library because of the following:
> 
> > The live display will persist for the duration of the context. You can update the renderable to update the display
> 
> https://rich.readthedocs.io/en/stable/live.html#basic-usage
> 
> > transient (bool, optional): Clear the renderable on exit (has no effect when screen=True). Defaults to False.
> 
> https://github.com/willmcgugan/rich/blob/f513abd35fdacccdc6fcbcc6989b5792b75ec97a/rich/live.py#L43
> 
> Setting `transient=False, screen=False` allows the UI to persist however it tends to flicker a lot whilst rendering. To achieve this without flickering, we might need to create another `render` that only performs a single render with the completed results once completed with the required settings.
> 
> ![image](https://user-images.githubusercontent.com/1443700/116929429-52b9b800-ac56-11eb-840e-af4f34e15dbd.png)

I tried an idea after looking at this and it seems to be working -- i set ```screen= not no_reload``` here

**Comment by apoclyps** [comment]
For a larger number of repositories and pull requests the screen flickering is still an issue in #76 

I've implemented an alternative solution in #78 - I would like to know your opinions on the solution.
