### ISSUE TITLE
[Feature] Display the users pull requests as "Mine" in approved

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/reviews#79]
**Is your feature request related to a problem? Please describe.**
When the `GITHUB_USER` is set, I would like to compare it to the user on a pull request to set the approved field to `Mine` displayed in yellow - when the pull request is authored by the GITHUB_USER provided.

**Describe the solution you'd like**
Any pull requests authored by the `GITHUB_USER` should always display `Mine` in yellow. 

Additionally, we should changed `CHANGES REQUESTED` to red. 

**Additional context**

For testing purposes, you can set the GitHub user to `apoclyps` and use this repository to find a pull request by `apoclyps`.

The change will be scoped to this area of the code as the `approved` field is already a string: https://github.com/apoclyps/reviews/blob/acfcd7463f5499ad7a1a239d44be1e6913a1780d/reviews/layout/helpers.py#L33-L37

![image](https://user-images.githubusercontent.com/1443700/117064094-a3481880-ad1d-11eb-8acc-4569638b53ce.png)

**Comment by ExpressHermes** [comment]
@apoclyps I would like to work on this issue.

**Comment by apoclyps** [comment]
@ExpressHermes if you are still interested in implementing this issue, let me know and I'll keep it assigned to you - otherwise it's up for grabs.
