### ISSUE TITLE
[Feature][Docs]: Setting up pre-commit for linting

### ISSUE THREAD

**Issue by yushao2** [apoclyps/reviews#92]
My apologies, I just noticed that pre-commit is already setup in this project -- maybe the docs can be updated to show how to set it up such that linting can be performed automatically when trying to make a commit?

Also, noticed that the pre-commit config only has black and isort, will try to add the other linters in (mypy, flake8, etc)

~~**Is your feature request related to a problem? Please describe.**~~
~~Would be great if a pre-commit hook can be set up to take care of linting before commit is allowed~~

~~**Describe the solution you'd like**~~
~~``pre-commit`` can be used (https://pre-commit.com/)~~

~~Have seen some open-source projects using it and I think it would be a nice feature to have.~~

~~**Additional context**~~
~~Reference for pylint's pre-commit config~~
~~https://github.com/PyCQA/pylint/blob/master/.pre-commit-config.yaml~~

**Comment by yushao2** [comment]
@apoclyps Kyle, I thought this might be good to have, but feel free to close this issue if you think otherwise 

I would take this up and give this a shot -- would probably help me in my upcoming role as a DevOps engineer :laughing:

**Comment by yushao2** [comment]
Oh, my mistake I didn't realise it's already in the repository :sweat:

**Comment by apoclyps** [comment]
@yushao2 congratulations on your upcoming devops role 🎉 

we could add it to the README as an optional dependancy for development as it will. Likely benefit others developers to know it can be included for pre commit hooks. 

A small update for What pre commit is, how we use it, steps to install it, and how to initialise it would be a great addition for this issue

**Comment by yushao2** [comment]
> @yushao2 congratulations on your upcoming devops role 
> 
> we could add it to the README as an optional dependancy for development as it will benefit other developers that are new to the project and pre commit hooks.
> 
> A small update for what pre commit is, how we use it, steps to install it, and how to initialise it would be a great addition for this issue
> 
> ```shell
> pip install pre-commit
> pre-commit init
> 
> pre-commit run --all
> ```

Let me push what I have, and continue tomorrow (it's 3.45 AM where I'm at :laughing: )

I've updated the pre-commit config to better reflect the linting steps described in README.md as well.

Thanks for taking a look at this

**Comment by apoclyps** [comment]
Good point, I didn't think to check timezone differences. Go get some sleep 👋 Consider all comments/feedback async - there is no urgency to action any of it immediately. always put yourself first :)

**Comment by apoclyps** [comment]
closed by #94
